stefangweichinger/ansible-rclone

defaults/main.yml, meta/main.yml, tasks/main.yml
- Added Cent OS/RedHat support
- Installs unzip if needed
- Use /usr/bin/rclon instead of /usr/sbin/rclone since it is in the default PATH in Ubuntu and Cent OS.
- Use GitHub downloads links for HTTPS support + the other link randomly timed out.
- Fixed outdated version
=> Cent OS/RedHat support, install unzip, use GitHub HTTPS download, fix version

vars/CentOS-6.yml
This command is provided by the "man" package on CentOS 6 so the
install will fail since "makewhatis" isn't a package in the default repositories on this OS.
Here is what I'm seeing on a fresh CentOS 6 installation:
```
[root@centos6 ~]# which makewhatis
/usr/sbin/makewhatis
[root@centos6 ~]# yum whatprovides /usr/sbin/makewhatis
Loaded plugins: fastestmirror
Determining fastest mirrors
* base: mirror.cogentco.com
* extras: mirror.vcu.edu
* updates: mirror.trouble-free.net
base                                                 | 3.7 kB     00:00     
base/primary_db                                      | 4.7 MB     00:00     
extras                                               | 3.4 kB     00:00     
extras/primary_db                                    |  29 kB     00:00     
updates …
```
=> Don't try to install makewhatis on CentOS 6

README.md, defaults/main.yml, tasks/main.yml
Updated README.md to tell users how to use the beta version. Beta version dowloads from
beta.rclone.org instead of github. This addresses #12
=> Add support for beta version

README.md, defaults/main.yml, tasks/beta.yml, tasks/main.yml, tasks/stable.yml
I've re-written the download logic to automatically get the latest stable version. rclone_version is no longer set as a default, but if provided as a variable, can be set to a specific version number or "beta" to install the latest beta version.
This will save you having to manually update the repo every time a new version is released.
=> Rewrite download section to automatically get the latest version.

tasks/main.yml
Noticed strange permissions after using the ansible copy module lately and found this in the docs:
```
You must either add a leading zero so that Ansible's YAML parser knows it is an octal number (like 0644 or 01777) or quote it (like '644' or '1777') so Ansible receives a string and can do its own conversion from string into number.
```
Same for the file-module, so I quoted these values now.
=> quote mode values, following ansible docs

tasks/main.yml, tasks/stable.yml
This downloads the SHA256SUMS and the GPG key of the author (which I sure hope is right!) and verifies the download.  This is good for security, but also integrity of the download.  I only did this on the stable side of things, I'm not sure if the betas are similarly signed and verified.
=> GPG verify stable rclone

.travis.yml, meta/main.yml, molecule/default/molecule.yml
Removed tests and meta-info for Ubuntu Linux 14.04, as it started breaking tests (seems that the repos went away etc). I assume that not too many people use that anymore anyway.
=> remove support for Ubuntu 14.04

README.md, vars/Pop!_OS.yml
I have created a new Pop_OS vars file and added it
=> Adding Pop_OS vars file

.travis.yml, molecule/travis/converge.yml, molecule/travis/molecule.yml
some testing:
* reintroduce separate travis scenario for the molecule tests
* this scenario should use `privileged: true` for a start
* add `fedora32` to the list of tests
fedora32 might need more specific settings (wait for systemd to start ...)
=> use travis scenario, with privileged containers, test F32 now

.travis.yml
molecule tests broke, because `docker-py` recently calls docker API 1.39 and Travis seems to only support 1.38.
Very likely something like this:
https://github.com/docker/docker-py/issues/2639
Switching back to `pip3 install docker==4.2.2` fixes my molecule runs in Travis.
=> Fix molecule tests

.github/workflows/molecule_test.yml, defaults/main.yml, molecule/default/molecule.yml, tasks/beta.yml, tasks/main.yml, tasks/stable.yml
- Adds ability to specify version when using beta release
- Adds logic to fail when the version in the rclone archive doesn't match what is expected
Fixes stefangweichinger/ansible-rclone#66
Fixes stefangweichinger/ansible-rclone#68
=> Add logic for release

.github/workflows/molecule_test.yml
Edit action workflow: only run the release step when the branch is master
=> only release code from master branch

tasks/install-config.yml
This is a follow-up of PR #85 : the config file installation must be run as root
=> run config file install as root

.github/workflows/molecule_test.yml, README.md, meta/main.yml
To reduce the number of test runs I remove older distros from the matrix of tested and supported operating systems /releases.
This doesn't mean that the role doesn't work there anymore!
=> reduce test matrix: drop centos7, ubuntu 16.x, fedora < 32

tasks/main.yml
* tasks/main.yml: Both tasks using the /etc/ansible/facts.d path
lacked privilege escalation.
This pull request fixes #107
=> Fix lack of privilege escalation

.github/workflows/molecule.yml
The action uses "master" as default branch, that one doesn't exist here.
So I have to set that to "main" instead.
=> add branch to release action

.github/workflows/molecule.yml, README.md
Added Ubuntu 22 to Molecule and README (also a slight grammar fix inside the latter)
=> Add Ubuntu 22 to supported platforms

tasks/main.yml
fixes #131 
If `rclone_config_location` is set to something common like `/etc` by the user, the former `mode: 0600` would have broken permissions for other software. This patch fixes this bug.
=> correct-permissions-of-config-directory

README.md, tasks/main.yml
This will enable users to act on the result of the rclone config setup task when including the role in a playbook, role, etc.
For example:
```yml
- name: Install and configure rclone
ansible.builtin.include_role:
name: stefangweichinger.ansible_rclone
vars:
rclone_configs:
- name: ExampleGoogleDriveRemote
properties:
type: drive
client_id: 12345
client_secret: 67890
- name: Restart rclone
ansible.builtin.systemd:
name: rclone.service
state: restarted
when: setup_rclone_config.changed
```
=> Register variable for rclone config setup task result

molecule/default/converge.yml, tasks/install-bin.yml, tasks/main.yml, templates/etc/ansible/facts.d/rclone.fact.j2
Thank you very much for this very useful role. In my setup I have to set `INJECT_FACTS_AS_VARS=false` in `ansible.cfg` which means that facts of the `ansible_facts` variable are not injected into the top level `vars` variable. To use this role I had to redefine the missing variables like this:
```
ansible_distribution: "{{ ansible_facts.distribution }}"
ansible_python: "{{ ansible_facts.python }}"
```
To avoid this kind of issues it would be better if this project uses the original variables names (e.g. `ansible_facts.distribution` instead of `ansible_distribution`). This PR tries to accomplish that.
=> Use original fact names instead of injected ones

.github/workflows/molecule.yml
add conditional to `release` job to not run on pull_request
fix `tags-ignore` syntax
do not trigger pr workflow on changes to `README.md`
add `test-archlinux` to needs on `release` job
=> do not run `release` job on pr

tasks/install-bin.yml
`ansible.builtin.copy` does not copy files if it already exists by default.
So, even when you want to upgrade, the file will not be overwritten.
=> Add `force` parameter to `ansible.builtin.copy` for rclone upgrading

tasks/main.yml, vars/default.yml
On some machines, include_vars fails because the distribution and OS family information is not public. (eg. shared rental server)
Add a default include file to execute subsequent tasks in such cases as well.
=> Add default include_vars to avoid not found error

.cz.yaml, CHANGELOG.md, README.md, defaults/main.yml, galaxy.yml, tasks/beta.yml, tasks/install-bin.yml, tasks/main.yml, tasks/stable.yml, vars/Archlinux.yml, vars/CentOS-6.yml, vars/CentOS-7.yml, vars/Debian.yml, vars/Fedora.yml, vars/Linuxmint.yml, vars/Pop!_OS.yml, vars/RedHat.yml, vars/SLES.yml, vars/Ubuntu.yml, vars/default.yml, vars/openSUSE Leap.yml
Closes #153
- Added support for running without `become: true` except for `rclone_mounts
- Added support for changing the location of manpages
- Added support for changing the location of binary
- Added support for avoiding installation of dependent packages (to avoid apt execution errors by non-root users)
=> Support installation by non-root users

README.md, tasks/mount.yml
* Define more relevant loop labels for mount tasks
* Document `rclone_mkdir`
=> Improvements to mount tasks & related docs

README.md, defaults/main.yml, tasks/mount.yml
Adds a task to ensure the local mount path exists with optionally configurable mode, owner, and group.
=> Ensure local mount path exists

.github/workflows/molecule.yml, molecule/default/converge.yml, tasks/beta.yml, tasks/install-bin.yml, tasks/main.yml, tasks/stable.yml
The role fails when Ansible is run in check mode because several directories do not exist.
>  msg: dest '/tmp/rclone_setup' must be an existing dir
I think its safe to create files under `/tmp` but the `rclone.fact` needs an exclusion.
=> Fix check mode
