stefangweichinger/ansible-rclone

- .travis.yml
- defaults/main.yml
- meta/main.yml
- tasks/main.yml
- tests/inventory
- tests/test.yml
- vars/CentOS-6.yml
- vars/Debian.yml
- vars/RedHat.yml
- vars/Ubuntu.yml
- Add full Travis testing for each OS.
- Refactor to easily extend OS support.
> Add support for all OS families

- tasks/main.yml
- vars/CentOS-6.yml
- vars/Debian.yml
- vars/RedHat.yml
- vars/Ubuntu.yml
> should fix issue #7

- vars/Linuxmint.yml
Please add the variable file for Linuxmint, it is based on Debian and Ubuntu. It work with the copy from Ubuntu fine.
> Linuxmint work like Ubuntu, I simple copy the file from Ubuntu and work

- defaults/main.yml
- tasks/main.yml
Fixes #16 
Could do the same for OS, too, but I don't need to at this time :)
> Extract var for rclone architecture

- .travis.yml
- meta/main.yml
- molecule/default/molecule.yml
Tests added to Travis and Molecule for:
* debian10
* fedora30
> tests for new Debian and Fedora releases

- .travis.yml
- meta/main.yml
- molecule/default/molecule.yml
* some more tricks with variables
* some more distros to test against
> new molecule setup

- README.md
- defaults/main.yml
- tasks/main.yml
- templates/rclone.conf.j2
Using a j2 template to create rclone.conf file from ansible variables.
> Add support for rclone.conf file

- README.md
- defaults/main.yml
- tasks/main.yml
- templates/rclone.conf.j2
Reverts stefangweichinger/ansible-rclone#31
Unfortunately this breaks the molecule tests.
Looking at it in detail now.
> Revert "Add support for rclone.conf file"

- tasks/main.yml
- tasks/stable.yml
Reverts stefangweichinger/ansible-rclone#26
> Revert "GPG verify stable rclone"

- README.md
- defaults/main.yml
- tasks/main.yml
- templates/rclone.conf.j2
Exact same PR as #31 except now I have fixed the failing tests which were just linting errors.
I've ran all the tests and confirmed they pass now.
> Add support for rclone.conf file, now with passing tests

- README.md
Hopefully this makes it more clear how the rclone_configs can be used.
> Add additional rclone_configs example to README

- tasks/main.yml
> issue #40: create config dir

- README.md
Greeting Stefan, sorry for the delay. Firstly, I hope you and your family are well at this testing time.
* Change embedded assets to actual path
* Document error around naming conventions
Is there anything we need to do to update the shields aspect of this? I've updated the URL, but they have not yet updated.
Closes #48
> Fixing role name in README and adding notice of name changes

- .github/workflows/ansible-lint.yml
- .travis.yml
- README.md
- meta/main.yml
- molecule/default/converge.yml
- molecule/default/molecule.yml
- molecule/playbook.yml
- molecule/travis/converge.yml
- molecule/travis/molecule.yml
- vars/Pop!_OS.yml
… and not as JSON object. see #45
> quote token variable to ensure it is interpreted as string

- .github/workflows/molecule_test.yml
- README.md
* updated README
* added gh action to publish to Ansible Galaxy
> CI improvement :: README edit, enable galaxy publish action

- .github/workflows/molecule_test.yml
https://github.com/actions/virtual-environments/issues/1816
> don't use ubuntu-latest for now

- tasks/beta.yml
- tasks/stable.yml
> Set mode to 0744 when extracting rclone zip file

- tasks/install-bin.yml
- tasks/install-config.yml
- tasks/main.yml
> split installation of binary and configs

- .github/workflows/molecule_test.yml
- README.md
> fix README: for beta you have to set rclone_release, not _version

- .github/FUNDING.yml
- README.md
- defaults/main.yml
- tasks/main.yml
Added possibility  to set the ownership of the file.
> control ownership on config file

- README.md
- defaults/main.yml
- tasks/main.yml
Reverts stefangweichinger/ansible-rclone#117
the formatting of the README isn't correct yet. Merged too soon.
> Revert "control ownership on config file"

- .github/FUNDING.yml
- README.md
- defaults/main.yml
- tasks/main.yml
fixes #117
Now with better README
> fixes #117

- .github/workflows/molecule.yml
- README.md
- handlers/main.yml
- meta/main.yml
- tasks/beta.yml
- tasks/install-bin.yml
- tasks/main.yml
- tasks/stable.yml
> Improve molecule tests

- .github/workflows/molecule.yml
- tasks/main.yml
> use Node16

- .github/workflows/molecule.yml
- README.md
> test against latest fedora releases

- tasks/install-bin.yml
> improving idempotency as discussed in #172
